
; COMDLG32 API calls (WideChar)

import comdlg32,\
       ChooseColor,'ChooseColorW',\
       ChooseFont,'ChooseFontW',\
       CommDlgExtendedError,'CommDlgExtendedError',\
       FindText,'FindTextW',\
       FormatCharDlgProc,'FormatCharDlgProc',\
       GetFileTitle,'GetFileTitleW',\
       GetOpenFileName,'GetOpenFileNameW',\
       GetSaveFileName,'GetSaveFileNameW',\
       LoadAlterBitmap,'LoadAlterBitmap',\
       PageSetupDlg,'PageSetupDlgW',\
       PrintDlg,'PrintDlgW',\
       ReplaceText,'ReplaceTextW',\
       WantArrows,'WantArrows',\
       dwLBSubclass,'dwLBSubclass',\
       dwOKSubclass,'dwOKSubclass'
