
; COMDLG32 API calls (ASCII)

import comdlg32,\
       ChooseColor,'ChooseColorA',\
       ChooseFont,'ChooseFontA',\
       CommDlgExtendedError,'CommDlgExtendedError',\
       FindText,'FindTextA',\
       FormatCharDlgProc,'FormatCharDlgProc',\
       GetFileTitle,'GetFileTitleA',\
       GetOpenFileName,'GetOpenFileNameA',\
       GetSaveFileName,'GetSaveFileNameA',\
       LoadAlterBitmap,'LoadAlterBitmap',\
       PageSetupDlg,'PageSetupDlgA',\
       PrintDlg,'PrintDlgA',\
       ReplaceText,'ReplaceTextA',\
       WantArrows,'WantArrows',\
       dwLBSubclass,'dwLBSubclass',\
       dwOKSubclass,'dwOKSubclass'
